name: 'Install Using PyPI'
description: 'Setup environment and install using the PyPI-based toolchain'

inputs:
  need-cartopy:
    description: 'Whether Cartopy is needed'
    required: true
    default: 'true'
  type:
    description: 'Whether test or doc build'
    required: true
  version-file:
    description: 'Name of the requirements file to use'
    required: true
    default: 'requirements.txt'
  python-version:
    description: 'What version of Python to use'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          ${{ inputs.version-file }}

    - name: Setup PROJ
      uses: ./.github/actions/setup-proj

    - name: Install CartoPy build dependencies
      if: ${{ inputs.need-cartopy == 'true' }}
      shell: bash
      run: sudo apt-get install -y libgeos-dev

    - name: Disable Shapely Wheels
      shell: bash
      run: echo "PIP_NO_BINARY=shapely" >> $GITHUB_ENV

    - name: Install required Python packages
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r ${{ inputs.version-file }}
        pip install flake8 coverage

    - name: Install jcclass in editable mode
      shell: bash
      run: |
        pip install -e .
